spring.application.name=eureka-server

server.port=${SERVER_PORT:8761}


# Disable self-registration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka dashboard settings
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://${eureka.instance.hostname}:${server.port}/eureka}

# Logging
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF
