server.port=${SERVER_PORT:8888}
spring.application.name=config-server

# \u2705 VERY IMPORTANT (disable git mode)
spring.profiles.active=native

# \u2705 Tell config server where local files are
spring.cloud.config.server.native.search-locations=${CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:classpath:/config}
