server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Cache-Control "no-store";
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:js|css|ico|png|jpg|jpeg|gif|svg|webp|woff2?)$ {
        expires -1;
        add_header Cache-Control "no-store";
        try_files $uri =404;
    }
}
